### Create user John
POST http://localhost:3000/user/register
Content-Type: application/json

{
    "name": "John",
    "email": "john@gmail.com",
    "password": "123456qq",
    "passwordConfirm": "123456qq"

}

### Get user profile by email

GET http://localhost:3000/v1/user/profile?email=john@gmail.com