GET  http://localhost:3000/tasks HTTP/1.1
Authorization: Bearer secret-token

###
GET  http://localhost:3000/tasks HTTP/1.1

###
GET  http://localhost:3000/tasks/8f217f3c-3254-4035-adc7-f6c8c272bd4c HTTP/1.1
Authorization: Bearer secret-token
###
POST http://localhost:3000/tasks
Content-Type: application/json
Authorization: Bearer secret-token
x-user-id: {"name": "Vasya"}

{
    "title": "world",
    "status": "pending",
    "description": "description"
    
}