services:
  db:
    image: postgres:15
    container_name: todo_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test
    ports:
      - '5432:5432'